#!/usr/bin/env python3
"""Derive the web brand assets from the master artwork in docs/Logos.

The masters are 1254x1254 truecolour PNGs with the background baked in: the
light set on white, the dark set on black, and neither with an alpha channel.
Shipping them as-is would put a white or black square behind the mark on every
surface, so this script keys the background out, crops to the artwork, and
hands the resize to sips (the only image tool this repository assumes).

It is stdlib-only on purpose: the brand assets must be reproducible on a clean
machine with nothing installed. Run it from the repository root:

    python3 apps/web/scripts/prepare-brand-assets.py

The output is committed, so a normal build never runs this. Re-run it only when
the masters change, and review the diff: the mark is the product's face.
"""

from __future__ import annotations

import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
MASTERS = ROOT / "docs" / "Logos"
WEB_ASSETS = ROOT / "apps" / "web" / "src" / "assets" / "brand"
WEB_PUBLIC = ROOT / "apps" / "web" / "public"
README_ASSETS = ROOT / "docs" / "brand"

# Pixels this far from the background colour are fully transparent; pixels this
# far are fully opaque. The ramp between them keeps the mark's edges from
# picking up a halo of the background it was drawn on.
FADE_START = 18
FADE_END = 64

# (master, output, longest-edge) for the assets that are actually loaded.
#
# The sizes are deliberately small. The mark is drawn at 39px in the shell, so a
# 512px copy would ship a megabyte of anti-aliased edge to render a chip; the
# favicon is 32px; the wordmark is documentation, not a layout element. Anything
# larger can be regenerated by raising the number here.
DERIVED = (
    ("Dawha-Logo.png", WEB_ASSETS / "mark.png", 192),
    ("Dawha-Text.png", README_ASSETS / "wordmark.png", 400),
    ("Dawha-Dircled.png", WEB_PUBLIC / "favicon-32.png", 32),
    ("Dawha-Dircled.png", WEB_PUBLIC / "apple-touch-icon-180.png", 180),
)


def read_png(path: Path) -> tuple[int, int, bytes]:
    """Return (width, height, RGB rows) for a non-interlaced 8-bit PNG.

    The scanline filters are reversed here, so callers get pixels rather than
    the compressed stream's own encoding.
    """
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path} is not a PNG")
    width = height = 0
    idat = bytearray()
    pos = 8
    while pos < len(data):
        (length,) = struct.unpack(">I", data[pos : pos + 4])
        kind = data[pos + 4 : pos + 8]
        body = data[pos + 8 : pos + 8 + length]
        if kind == b"IHDR":
            width, height, depth, colour, _, _, interlace = struct.unpack(">IIBBBBB", body)
            if depth != 8 or colour != 2 or interlace != 0:
                raise ValueError(f"{path} is not 8-bit truecolour; this script only handles that")
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break
        pos += 12 + length
    return width, height, unfilter(width, height, zlib.decompress(bytes(idat)))


def unfilter(width: int, height: int, raw: bytes) -> bytearray:
    """Reverse the five PNG scanline filters."""
    stride = width * 3
    out = bytearray(stride * height)
    previous = bytearray(stride)
    pos = 0
    for row in range(height):
        filter_type = raw[pos]
        pos += 1
        line = bytearray(raw[pos : pos + stride])
        pos += stride
        if filter_type == 1:
            for i in range(3, stride):
                line[i] = (line[i] + line[i - 3]) & 0xFF
        elif filter_type == 2:
            for i in range(stride):
                line[i] = (line[i] + previous[i]) & 0xFF
        elif filter_type == 3:
            for i in range(stride):
                left = line[i - 3] if i >= 3 else 0
                line[i] = (line[i] + ((left + previous[i]) >> 1)) & 0xFF
        elif filter_type == 4:
            for i in range(stride):
                left = line[i - 3] if i >= 3 else 0
                up = previous[i]
                upper_left = previous[i - 3] if i >= 3 else 0
                estimate = left + up - upper_left
                da, db, dc = abs(estimate - left), abs(estimate - up), abs(estimate - upper_left)
                if da <= db and da <= dc:
                    predictor = left
                elif db <= dc:
                    predictor = up
                else:
                    predictor = upper_left
                line[i] = (line[i] + predictor) & 0xFF
        elif filter_type != 0:
            raise ValueError(f"unknown PNG filter {filter_type}")
        out[row * stride : (row + 1) * stride] = line
        previous = line
    return out


def write_rgba(path: Path, width: int, height: int, pixels: bytes) -> None:
    """Write a minimal 8-bit RGBA PNG: IHDR, IDAT, IEND and nothing else."""
    raw = bytearray()
    stride = width * 4
    for row in range(height):
        raw.append(0)
        raw += pixels[row * stride : (row + 1) * stride]

    def chunk(kind: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body))
            + kind
            + body
            + struct.pack(">I", zlib.crc32(kind + body) & 0xFFFFFFFF)
        )

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )


def key_background(master: Path) -> tuple[int, int, int, int, int, bytearray]:
    """Return (source_width, left, top, width, height, rgba) with the background transparent.

    The margin is left in the buffer and the bounds are returned, so the crop is
    a straight copy of rows the keying pass has already found.
    """
    width, height, rgb = read_png(master)
    stride = width * 3
    # The four corners are background in every master in this set; averaging
    # them keeps one stray pixel from deciding the key colour.
    corners = [
        rgb[0:3],
        rgb[(width - 1) * 3 : width * 3],
        rgb[(height - 1) * stride : (height - 1) * stride + 3],
        rgb[height * stride - 3 : height * stride],
    ]
    key = tuple(sum(pixel[i] for pixel in corners) // len(corners) for i in range(3))

    rgba = bytearray(width * height * 4)
    left, top, right, bottom = width, height, -1, -1
    for row in range(height):
        base = row * stride
        out = row * width * 4
        for column in range(width):
            offset = base + column * 3
            r, g, b = rgb[offset], rgb[offset + 1], rgb[offset + 2]
            distance = max(abs(r - key[0]), abs(g - key[1]), abs(b - key[2]))
            if distance >= FADE_END:
                alpha = 255
            elif distance <= FADE_START:
                alpha = 0
            else:
                alpha = round((distance - FADE_START) / (FADE_END - FADE_START) * 255)
            target = out + column * 4
            rgba[target : target + 4] = bytes((r, g, b, alpha))
            if alpha:
                if column < left:
                    left = column
                if column > right:
                    right = column
                if row < top:
                    top = row
                if row > bottom:
                    bottom = row
    if right <= left or bottom <= top:
        raise ValueError(f"{master} produced an empty image; the key colour may be wrong")
    return width, left, top, right - left + 1, bottom - top + 1, rgba


def crop(rgba: bytearray, source_width: int, left: int, top: int, width: int, height: int) -> bytes:
    out = bytearray(width * height * 4)
    for row in range(height):
        source = ((top + row) * source_width + left) * 4
        out[row * width * 4 : (row + 1) * width * 4] = rgba[source : source + width * 4]
    return bytes(out)


def main() -> int:
    for target in (WEB_ASSETS, WEB_PUBLIC, README_ASSETS):
        target.mkdir(parents=True, exist_ok=True)

    for name, destination, size in DERIVED:
        master = MASTERS / name
        if not master.exists():
            print(f"missing master: {master}", file=sys.stderr)
            return 1
        source_width, left, top, width, height, rgba = key_background(master)
        trimmed = crop(rgba, source_width, left, top, width, height)

        with tempfile.TemporaryDirectory() as scratch:
            keyed = Path(scratch) / "keyed.png"
            write_rgba(keyed, width, height, trimmed)
            subprocess.run(
                ["sips", "-s", "format", "png", "-Z", str(size), str(keyed), "--out", str(destination)],
                check=True,
                capture_output=True,
            )
        print(f"{name} -> {destination.relative_to(ROOT)} ({width}x{height} keyed, longest edge {size})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
